version: 2.1
jobs:
  build:
    docker:
      - image: ${AWS_ACC_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/python-service:latest
        environment:
          VAR_2: PLACE_HOLDER2
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
              python3 -m venv env
              . env/bin/activate
              apt update
              pip install --upgrade pip
              pip install -r ops/requirements.txt
              pip show boto3
              python ops/get_ssm.py
              chmod 400 ~/.ssh/id_rsa
      - run:
          name: Run Tests
          command: |
              . env/bin/activate
              export PYTHONPATH=.
              export TEST_MODE=1

      - run:
          name: Whitelist IP
          command: |
            PUBLIC_IP=$(curl ifconfig.me)
            aws ec2 authorize-security-group-ingress \
                --group-id ${TF_SECURITY_GROUP} \
                --protocol tcp \
                --port 22 \
                --cidr ${PUBLIC_IP}/32

      - run:
          name: Test kubectl
          command: |
            ansible-playbook ansible/playbooks/locals.yml
            export KUBECONFIG=~/.kube/kubeconfig
            kubectl get nodes --show-labels

      - run:
          name: Run Terrraform init
          command: terraform init

      - run:
          name: Run Terrraform plan
          command: terraform plan

      - run:
          name: Run Terrraform to provision security group and routing tables
          command: |
            # when AUTO_DEPLOY is for master branch only
            if [ $CIRCLE_BRANCH = '$CIRCLE_BRANCH' ]; then
              echo "Terraform will not apply changes from $CIRCLE_BRANCH"
              echo "Terraform apply only from master branch, submit a pull request"
              AUTO_DEPLOY=none
            elif [ $CIRCLE_BRANCH = 'integration-branch' ]; then
              AUTO_DEPLOY="-auto-approve"
              terraform apply $AUTO_DEPLOY
            fi
#workflows:
#  version: 2.1
#  build:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: master