apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app-service
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-app:
    spec:
      containers:
      - name: python-service
        image: ${ACC_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000