apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-service
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
      - name: python-service
        image: python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000