---
apiVersion: apps/v1
kind: Pod
metadata:
  name: flask-app.44-labs.com
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name:
        image: python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000