---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app.44-labs.com
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: ${AWS_ACC_NUMBER}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 5000