apiVersion: v1
kind: Service
metadata:
  name: flask-app-44-labs-service
spec:
  ports:
  - port: 80
    targetPort: flask-app-port
    protocol: TCP
  selector:
      app: flask-app
  type: LoadBalancer